name: Continuous Integration

on:
  pull_request:
  workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v1
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Lint
      run: npm run lint

  commit-lint:

    runs-on: ubuntu-18.04

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: wagoid/commitlint-github-action@v2.0.2
      with:
        helpURL: https://github.com/PauloGoncalvesBH/ServeRest/blob/trunk/.github/CONTRIBUTING.md

  test-api:

    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node: [10, 12, 14]

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js v${{ matrix.node }} Setup
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: API Test
      run: npm test
    - name: Update Codecov Report
      uses: codecov/codecov-action@v1.0.13

  test-mutation-diff:

    runs-on: ubuntu-18.04

    steps:
    - name: Project checkout
      uses: actions/checkout@v2
    - name: Node.js Setup
      uses: actions/setup-node@v1
    - name: Installation of Node.js dependencies
      run: npm ci
    - name: Mutation Test - Changed files in the branch
      run: |
        git fetch origin trunk:refs/remotes/origin/trunk
        npm run test:mutation:diff
      env:
        STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}